apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: jfrog  upload actions
inputs:
  url:  # id of input
    description: 'Url'
    required: true
  username:  # id of input
    description: 'username - (Optional if token is provided)'
    required: false
    default: ''
  password:  # id of input
    description: 'password - (Optional if token is provided)'
    required: false
    default: ''
  token:  # id of input
    description: 'token - (Optional if username and password is provided)'
    required: false
    default: ''
  artifactory-path:  # id of input
    description: 'artifactory path'
    required: true
  file-path:  # id of input
    description: 'file path'
    required: true
  send-artifact-info:
      default: 'false'
      description: >
        If set, artifact info is sent to CloudBees Unify.
        Type: Boolean
      required: false
  artifact-name:
      description: >
        If set, artifact name is sent to CloudBees Unify.
      required: false
  artifact-version:
      description: >
        If set, artifact version is sent to CloudBees Unify.
      required: false
  commit:
    description: >
      The commit ID from the source repository, used when registering the build artifact in CloudBees Unify.
    default: ${{ cloudbees.scm.sha }}
    required: false
  repository-url:
    description: >
      The clone URL of the source repository, used when registering the build artifact in CloudBees Unify.
    default: ${{ cloudbees.scm.repositoryUrl }}
    required: false
  ref:
    description: >
      The ref or branch of the source repository, used when registering the build artifact in CloudBees Unify.
    default: ${{ cloudbees.scm.ref }}
    required: false
  component-id:
    description: >
      The ID of the component associated with the artifact. If not provided, the artifact is registered with the component of the current workflow run.
    default: ${{ cloudbees.component.id }}
    required: false

outputs:
  artifact-id:
    value: ${{ steps.run-jfrog-upload-action.outputs.artifact-id }}
    description: "The unique identifier of the artifact."

runs:
  using: composite
  steps:
    - id: run-jfrog-upload-action
      name: run-jfrog-upload-action
      uses: docker://public.ecr.aws/l7o7z1g8/actions/jfrog-actions:CBP-27024-5469c99014e44eabc958e1cd02e740099435c7fc
      shell: sh
      env:
        CONFIG_JSON: '{"metaInfo":{"srcType":"upload","url":"${{ inputs.url }}","username":"${{ inputs.username }}","password":"${{ inputs.password }}","token":"${{ inputs.token }}","artifactoryPath":"${{ inputs.artifactory-path }}","filePath":"${{ inputs.file-path }}","send-artifact-info":${{ inputs.send-artifact-info }},"artifact-name":"${{ inputs.artifact-name }}","artifact-version":"${{ inputs.artifact-version }}","commit":"${{ inputs.commit }}","repository-url":"${{ inputs.repository-url }}","ref":"${{ inputs.ref }}","component-id":"${{ inputs.component-id }}"}}'
        CLOUDBEES_API_URL: ${{ cloudbees.api.url }}
        CLOUDBEES_API_TOKEN: ${{ cloudbees.api.token }}
        CLOUDBEES_RUN_ID: ${{ cloudbees.run_id }}
        CLOUDBEES_RUN_ATTEMPT: ${{ cloudbees.run_attempt }}
      run: |
        set -x
        cd /app
        ./jfrog_artifactory_actions_app invoke -i $CONFIG_JSON
